### ISSUE TITLE
normalize results to 250 rpm

### ISSUE THREAD

**Issue by joel-loube** [joel-loube/rocotest#1]
is this a straight linear relationship?

reference: http://foxed.ca/index.php?page=rotarycalc

**Comment by patrickmcquay** [comment]
are there formulas for this? Do we need to do this since we are outputting the RPM already?

**Comment by joel-loube** [comment]
250 rpm is the standard that all other testers normalize to. the official mazda tester I believe has a 'normalize to 250' button that you can toggle on and off.

**Comment by patrickmcquay** [comment]
looks like the formula for this is:

corrected pressure = raw pressure * (8.6 + (-0.048 * rpm) + (0.000054 * sq(rpm)));

**Comment by patrickmcquay** [comment]
correction, the formula is raw pressure +, not *.

**Comment by patrickmcquay** [comment]
fixed by a45de1e5c4f3fc28132073f8f12287c4578f656b
