### ISSUE TITLE
compensate for atmosphereic pressure

### ISSUE THREAD

**Issue by joel-loube** [joel-loube/rocotest#2]
take an initial reading before the compression pulses, adjust results accordingly

**Comment by patrickmcquay** [comment]
What would this get us? I'm not even really sure how this would be done?

**Comment by joel-loube** [comment]
basically normalize the result to 'sea level'. testing at higher elevation will show 'artificially' lower results otherwise. technically air temperature should also be accounted for but we don't have a temp sensor.

**Comment by patrickmcquay** [comment]
looks like the way to do this is just take some measurements when the device boots and then subtract those from the raw measurements. Seems simple enough.

**Comment by patrickmcquay** [comment]
fixed by 12d4db0345315b4d8e8bfd12903d2561f320a1b6
